<?php

namespace Hhxsv5\LaravelS\Tests;

class TestCase extends \PHPUnit\Framework\TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}