{
 "title": "LaravelS All Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(swoole_connection_num{application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 1分钟"
    },
    {
     "expr": "sum(system_load_average_5m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 5分钟"
    },
    {
     "expr": "sum(system_load_average_15m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 15分钟"
    }
   ]
  },
  {
   "title": "连接统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_connection_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  {
   "title": "总QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method)",
     "legendFormat": "{{application}}-{{method}}"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "sum(irate(swoole_request_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}-Swoole"
    }
   ]
  },
  {
   "title": "QPS排行榜",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Worker统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}-Worker总数"
    },
    {
     "expr": "swoole_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}-空闲Worker数"
    }
   ]
  },
  {
   "title": "Task Worker统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_task_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}-Worker总数"
    },
    {
     "expr": "swoole_task_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}-空闲Worker数"
    },
    {
     "expr": "swoole_tasking_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}-排队任务数"
    }
   ]
  },
  {
   "title": "5XX统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "5XX错误率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri) / sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "耗时排行榜",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_sum{application=\"$application\"}[1m])) by (application, method, uri)/sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "请求量排行榜",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(http_server_requests_seconds_count{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "APCu内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(apcu_seg_size{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 总共"
    },
    {
     "expr": "sum(apcu_avail_mem{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 可用"
    }
   ]
  }
 ]
}