{
 "title": "LaravelS Service Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(swoole_connection_num{application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 1m"
    },
    {
     "expr": "sum(system_load_average_5m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 5m"
    },
    {
     "expr": "sum(system_load_average_15m{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} 15m"
    }
   ]
  },
  {
   "title": "Connection Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_connection_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method)",
     "legendFormat": "{{application}}-{{method}}"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "sum(irate(swoole_request_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}-Swoole"
    }
   ]
  },
  {
   "title": "Top RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Worker Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "swoole_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Idle"
    }
   ]
  },
  {
   "title": "Task Worker Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_task_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "swoole_task_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Idle"
    },
    {
     "expr": "swoole_tasking_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Tasking"
    }
   ]
  },
  {
   "title": "Total 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "5xx Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(irate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri) / sum(irate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Top Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_sum{application=\"$application\"}[1m])) by (application, method, uri)/sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "APCu Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(apcu_seg_size{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "sum(apcu_avail_mem{application=\"$application\",instance=~\"$instance\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} Available"
    }
   ]
  },
  {
   "title": "Bottom Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, sum(http_server_requests_seconds_count{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(http_server_requests_seconds_count{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "dtdhms" }
   ],
   "targets": [
    {
     "expr": "time()-swoole_start_time{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  }
 ]
}